
import React from 'react';

interface TermsProps {
  onNavigate: (page: string) => void;
}

const Terms: React.FC<TermsProps> = ({ onNavigate }) => {
  return (
    <div className="min-h-screen bg-white font-sans text-brand-charcoal selection:bg-brand-gold/20">
      {/* Navigation */}
      <nav className="sticky top-0 z-50 bg-white/95 backdrop-blur-md border-b border-brand-sage/20 px-6 py-4">
        <div className="max-w-5xl mx-auto flex justify-between items-center">
          <div className="flex items-center gap-3 cursor-pointer" onClick={() => onNavigate('landing')}>
            <div className="w-8 h-8 bg-brand-charcoal rounded-lg flex items-center justify-center text-white font-black text-sm">A</div>
            <span className="text-lg font-black tracking-tighter text-brand-charcoal uppercase">TERMS OF SERVICE</span>
          </div>
          <button 
            onClick={() => onNavigate('landing')} 
            className="text-[10px] font-black uppercase tracking-widest text-brand-muted hover:text-brand-gold transition-colors"
          >
            Close
          </button>
        </div>
      </nav>

      {/* Hero Section */}
      <header className="py-20 px-6 bg-brand-sage/5 border-b border-brand-sage/10">
        <div className="max-w-4xl mx-auto text-center space-y-6 animate-fade-in">
          <div className="inline-block p-3 bg-white rounded-2xl shadow-sm mb-4">
            <svg xmlns="http://www.w3.org/2000/svg" className="w-8 h-8 text-brand-charcoal" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
          </div>
          <h1 className="text-4xl md:text-5xl font-black text-brand-charcoal uppercase tracking-tighter">
            Terms of Service
          </h1>
          <p className="text-lg text-brand-muted font-medium max-w-2xl mx-auto leading-relaxed">
            These terms govern your access to and use of the Athenix platform. Please read them carefully before initializing any terminal session.
          </p>
          <p className="text-[10px] font-black text-brand-muted uppercase tracking-[0.2em] pt-4 opacity-60">
            Last Updated: March 2024
          </p>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-4xl mx-auto px-6 py-16 space-y-12">
        
        {/* Section 1: Acceptance */}
        <section className="athenix-card p-10 space-y-4 border-l-4 border-l-brand-charcoal">
          <h2 className="text-sm font-black text-brand-charcoal uppercase tracking-[0.2em]">1. Acceptance of Terms</h2>
          <p className="text-sm text-brand-muted leading-loose font-medium">
            By accessing, registering for, or using the Athenix platform ("Service"), you certify that you have read, understood, and agree to be bound by these Terms of Service. If you do not agree to these terms, you are prohibited from using the Service.
          </p>
        </section>

        {/* Section 2: Eligibility */}
        <section className="space-y-4">
          <h2 className="text-sm font-black text-brand-charcoal uppercase tracking-[0.2em] pl-4 border-l-2 border-brand-sage/30">2. Eligibility</h2>
          <p className="text-sm text-brand-muted leading-loose font-medium">
            You represent that you are of legal age in your jurisdiction to form a binding contract. Athenix is an educational and analytical tool; <strong className="text-brand-charcoal">we do not provide financial advice, brokerage services, or investment management.</strong>
          </p>
        </section>

        {/* Section 3: Service Description */}
        <section className="space-y-4">
          <h2 className="text-sm font-black text-brand-charcoal uppercase tracking-[0.2em] pl-4 border-l-2 border-brand-sage/30">3. Service Description</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="p-6 bg-white border border-brand-sage/20 rounded-xl">
              <h3 className="text-xs font-black text-brand-charcoal uppercase tracking-widest mb-2">AI Analysis</h3>
              <p className="text-xs text-brand-muted font-medium leading-relaxed">Automated market analysis generated by neural networks. These are informational only.</p>
            </div>
            <div className="p-6 bg-white border border-brand-sage/20 rounded-xl">
              <h3 className="text-xs font-black text-brand-charcoal uppercase tracking-widest mb-2">No Guarantees</h3>
              <p className="text-xs text-brand-muted font-medium leading-relaxed">Athenix does not guarantee profit or prevention of loss. All trading carries risk.</p>
            </div>
          </div>
        </section>

        {/* Section 4: User Responsibilities */}
        <section className="space-y-4">
          <h2 className="text-sm font-black text-brand-charcoal uppercase tracking-[0.2em] pl-4 border-l-2 border-brand-sage/30">4. User Responsibilities</h2>
          <div className="athenix-card p-8 bg-brand-sage/5 border-dashed">
            <ul className="space-y-4">
              {[
                "You agree to use the platform for lawful purposes only.",
                "You will not misuse AI outputs or present them as professional financial advice.",
                "You will not attempt to reverse-engineer, scrape, or exploit the platform.",
                "You are responsible for maintaining the security of your account credentials."
              ].map((point, i) => (
                <li key={i} className="flex gap-4 items-start">
                  <div className="w-1.5 h-1.5 bg-brand-charcoal rounded-full mt-2 shrink-0"></div>
                  <span className="text-sm text-brand-muted font-medium leading-relaxed">{point}</span>
                </li>
              ))}
            </ul>
          </div>
        </section>

        {/* Section 5: Subscriptions & Payments */}
        <section className="space-y-4">
          <h2 className="text-sm font-black text-brand-charcoal uppercase tracking-[0.2em] pl-4 border-l-2 border-brand-sage/30">5. Subscriptions & Payments</h2>
          <p className="text-sm text-brand-muted leading-loose font-medium">
            Access to Athenix is provided on a subscription basis (Lite, Pro, Elite). Payments are billed monthly. All subscriptions are non-refundable unless required by applicable consumer law. We reserve the right to modify pricing with reasonable notice to active users.
          </p>
        </section>

        {/* Section 6: Tokens & Usage */}
        <section className="space-y-4">
          <h2 className="text-sm font-black text-brand-charcoal uppercase tracking-[0.2em] pl-4 border-l-2 border-brand-sage/30">6. Tokens & Usage</h2>
          <p className="text-sm text-brand-muted leading-loose font-medium">
            Platform features consume "Tokens" (Analysis or Education units). Tokens reset monthly based on your plan. Additional tokens may be purchased. Systematic abuse of the token system may result in account suspension.
          </p>
        </section>

        {/* Section 7: Intellectual Property */}
        <section className="space-y-4">
          <h2 className="text-sm font-black text-brand-charcoal uppercase tracking-[0.2em] pl-4 border-l-2 border-brand-sage/30">7. Intellectual Property</h2>
          <p className="text-sm text-brand-muted leading-loose font-medium">
            Athenix owns all rights, title, and interest in the platform, including branding, logos, code, AI output structures, and educational content. You may not copy, redistribute, or create derivative works without explicit written permission.
          </p>
        </section>

        {/* Section 8: Disclaimers */}
        <section className="athenix-card p-8 bg-brand-warning/5 border-brand-warning/20">
          <div className="flex items-center gap-4 mb-4">
            <svg xmlns="http://www.w3.org/2000/svg" className="w-6 h-6 text-brand-warning" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
            </svg>
            <h2 className="text-sm font-black text-brand-charcoal uppercase tracking-[0.2em]">8. Critical Disclaimers</h2>
          </div>
          <p className="text-sm text-brand-muted leading-loose font-medium">
            Trading involves a substantial risk of loss and is not suitable for every investor. <strong className="text-brand-charcoal">Athenix is not responsible for any financial losses incurred.</strong> All AI outputs are probabilistic and should be used as one of many tools in your decision-making process.
          </p>
        </section>

        {/* Section 9: Limitation of Liability */}
        <section className="space-y-4">
          <h2 className="text-sm font-black text-brand-charcoal uppercase tracking-[0.2em] pl-4 border-l-2 border-brand-sage/30">9. Limitation of Liability</h2>
          <p className="text-sm text-brand-muted leading-loose font-medium">
            To the maximum extent permitted by law, Athenix shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or goodwill.
          </p>
        </section>

        {/* Section 10: Termination */}
        <section className="space-y-4">
          <h2 className="text-sm font-black text-brand-charcoal uppercase tracking-[0.2em] pl-4 border-l-2 border-brand-sage/30">10. Termination</h2>
          <p className="text-sm text-brand-muted leading-loose font-medium">
            We reserve the right to suspend or terminate your account immediately, without prior notice, if you breach these Terms. You may cancel your subscription at any time via the billing dashboard.
          </p>
        </section>

        {/* Section 11: Governing Law */}
        <section className="space-y-4">
          <h2 className="text-sm font-black text-brand-charcoal uppercase tracking-[0.2em] pl-4 border-l-2 border-brand-sage/30">11. Governing Law</h2>
          <p className="text-sm text-brand-muted leading-loose font-medium">
            These terms shall be governed by and construed in accordance with applicable international and local regulations.
          </p>
        </section>

        {/* Section 12: Contact */}
        <section className="mt-12 p-8 bg-brand-sage/10 rounded-2xl text-center space-y-4">
          <h2 className="text-sm font-black text-brand-charcoal uppercase tracking-[0.2em]">12. Contact Legal Team</h2>
          <p className="text-sm text-brand-muted font-medium">
            For questions regarding these Terms of Service:
          </p>
          <a href="mailto:help@athenixflow.com" className="inline-block px-6 py-3 bg-white border border-brand-sage/30 rounded-xl text-xs font-black text-brand-charcoal uppercase tracking-widest hover:border-brand-gold transition-colors">
            help@athenixflow.com
          </a>
        </section>

      </main>

      <footer className="py-10 text-center border-t border-brand-sage/20">
        <p className="text-[9px] font-black text-brand-muted uppercase tracking-[0.3em]">
          &copy; {new Date().getFullYear()} Athenix Neural Network
        </p>
      </footer>
    </div>
  );
};

export default Terms;
